# Generated by Django 5.2.7 on 2025-10-21 07:20

import common.models
import django.db.models.deletion
import django.utils.timezone
import tags.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uid', models.CharField(default=common.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('name', models.CharField(help_text='标签名称，如‘生活’‘工作’', max_length=50, unique=True)),
                ('color', models.CharField(default=tags.models.generate_tag_color, help_text='标签颜色（十六进制，如#ff0000）', max_length=7)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'user_tags',
                'ordering': ['-update_time'],
                'unique_together': {('name', 'user', 'is_deleted')},
            },
        ),
    ]
