# Generated by Django 5.2.7 on 2025-10-21 08:33

import tags.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=tags.models.generate_tag_color, help_text='十六进制，如#ff0000', max_length=7, verbose_name='颜色'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text="标签名称，如'生活''工作'", max_length=50, verbose_name='名称'),
        ),
    ]
