# Generated by Django 5.2.7 on 2025-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_color_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sort_order',
            field=models.FloatField(default=0, verbose_name='排序'),
        ),
    ]
