# Generated by Django 5.2.7 on 2025-11-13 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_update_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'is_deleted', '-update_time'], name='tag_user_deleted_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'is_deleted', 'name'], name='tag_user_deleted_name_idx'),
        ),
    ]
