# Generated by Django 5.2.7 on 2025-10-15 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='上传时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True, verbose_name='前缀')),
                ('hashed_key', models.CharField(editable=False, max_length=150, verbose_name='密钥')),
                ('revoked', models.BooleanField(default=False, help_text='吊销的 API 密钥将无法再被客户端使用。', verbose_name='已吊销')),
                ('expiry_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'API keys',
                'verbose_name_plural': 'API keys',
                'db_table': 'user_api_keys',
                'ordering': ('-create_time',),
            },
        ),
    ]
