# Generated by Django 5.2.7 on 2025-10-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ('-create_time',), 'verbose_name': '密钥', 'verbose_name_plural': '密钥'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='key',
            field=models.CharField(default=1, editable=False, max_length=150, unique=True, verbose_name='密钥'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='hashed_key',
            field=models.CharField(editable=False, max_length=150, verbose_name='哈希'),
        ),
    ]
