# Generated by Django 5.2.7 on 2025-10-15 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_apikey_options_apikey_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='latest_used_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最新使用日期'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='使用次数'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='create_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='revoked',
            field=models.BooleanField(default=False, help_text='吊销的 API 密钥将无法再被客户端使用。', verbose_name='吊销'),
        ),
    ]
