# Generated by Django 5.2.7 on 2025-11-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_apikey_latest_used_date_apikey_usage_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
