# Generated by Django 6.0 on 2026-01-14 07:20

import bbtalk.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='显示名称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('authelia_user_id', models.CharField(blank=True, db_index=True, help_text='来自 Authelia 认证服务的用户唯一标识', max_length=255, null=True, unique=True, verbose_name='Authelia用户ID')),
                ('groups', models.JSONField(blank=True, default=list, verbose_name='用户组')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'cb_users',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['authelia_user_id'], name='user_authelia_idx'), models.Index(fields=['username'], name='user_username_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=bbtalk.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('name', models.CharField(help_text='标签名称', max_length=50, verbose_name='名称')),
                ('color', models.CharField(default=bbtalk.models.generate_tag_color, help_text='十六进制，如#ff0000', max_length=7, verbose_name='颜色')),
                ('sort_order', models.FloatField(default=0, verbose_name='排序')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bbtalk.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'cb_user_tags',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='BBTalk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=bbtalk.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('content', models.TextField(help_text='支持 Markdown', verbose_name='内容')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '仅自己可见')], default='private', max_length=16, verbose_name='可见性')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='附件列表，存储附件元信息的字典列表', verbose_name='附件')),
                ('context', models.JSONField(blank=True, default=dict, help_text='存储 GPS/天气/设备等上下文信息', verbose_name='上下文信息')),
                ('tags', models.ManyToManyField(db_constraint=False, db_table='cb_bbtalk_tags_relations', related_name='bbtalks', to='bbtalk.tag', verbose_name='标签')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bbtalk.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '碎碎念',
                'verbose_name_plural': '碎碎念',
                'db_table': 'cb_user_bbtalks',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', '-update_time'], name='tag_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tag_user_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='bbtalk',
            index=models.Index(fields=['user', '-update_time'], name='bbtalk_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bbtalk',
            index=models.Index(fields=['user', '-create_time'], name='bbtalk_user_create_idx'),
        ),
    ]
