# Generated by Django 5.2.7 on 2025-10-21 07:20

import common.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBTalk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uid', models.CharField(default=common.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('content', models.TextField(help_text='支持 Markdown', verbose_name='内容')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '仅自己可见')], default='private', max_length=16, verbose_name='可见性')),
                ('context', models.JSONField(blank=True, default=dict, help_text='存储 GPS/天气/设备等上下文信息', verbose_name='上下文信息')),
                ('media', models.ManyToManyField(db_table='bbtalk_media_relations', related_name='bbtalks', to='media.media', verbose_name='媒体附件')),
                ('tags', models.ManyToManyField(db_table='bbtalk_tags_relations', related_name='bbtalks', to='tags.tag', verbose_name='标签')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '碎碎念',
                'verbose_name_plural': '碎碎念',
                'db_table': 'user_bbtalks',
                'ordering': ['-update_time'],
            },
        ),
    ]
