# Generated by Django 6.0 on 2026-01-20 03:08

import bbtalk.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='显示名称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理员')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'cb_users',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['username'], name='user_username_idx'), models.Index(fields=['email'], name='user_email_idx'), models.Index(fields=['is_active', '-create_time'], name='user_active_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('storage_path', models.CharField(max_length=500, verbose_name='存储路径')),
                ('mime_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('size', models.BigIntegerField(help_text='单位：字节', verbose_name='文件大小')),
                ('owner_id', models.CharField(db_index=True, max_length=100, verbose_name='所有者ID')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='公开文件可被任何人访问', verbose_name='公开访问')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'cb_attachments',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['owner_id', 'created_at'], name='cb_attachme_owner_i_732c09_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=bbtalk.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('name', models.CharField(help_text='标签名称', max_length=50, verbose_name='名称')),
                ('color', models.CharField(default=bbtalk.models.generate_tag_color, help_text='十六进制，如#ff0000', max_length=7, verbose_name='颜色')),
                ('sort_order', models.FloatField(default=0, verbose_name='排序')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'cb_tags',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='BBTalk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=bbtalk.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('content', models.TextField(help_text='支持 Markdown', verbose_name='内容')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '仅自己可见')], default='private', max_length=16, verbose_name='可见性')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='附件列表，存储附件元信息的字典列表', verbose_name='附件')),
                ('context', models.JSONField(blank=True, default=dict, help_text='存储 GPS/天气/设备等上下文信息', verbose_name='上下文信息')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('tags', models.ManyToManyField(blank=True, db_constraint=False, db_table='cb_bbtalk_tag_relations', related_name='bbtalks', to='bbtalk.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '碎碎念',
                'verbose_name_plural': '碎碎念',
                'db_table': 'cb_bbtalks',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='身份ID')),
                ('identity_type', models.CharField(choices=[('password', '密码登录'), ('oauth', 'OAuth登录'), ('wechat', '微信登录'), ('email_code', '邮箱验证码')], max_length=32, verbose_name='身份类型')),
                ('identifier', models.CharField(help_text='密码登录存username，OAuth存provider+openid，邮箱登录存email', max_length=255, verbose_name='标识符')),
                ('credential', models.CharField(blank=True, help_text='密码登录存密码哈希，OAuth存access_token，验证码登录不存', max_length=255, verbose_name='凭证')),
                ('provider', models.CharField(blank=True, help_text='如: github, google, wechat', max_length=32, verbose_name='OAuth提供商')),
                ('provider_user_id', models.CharField(blank=True, max_length=255, verbose_name='第三方用户ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否为主身份')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '身份',
                'verbose_name_plural': '身份',
                'db_table': 'cb_identities',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['user', 'identity_type'], name='identity_user_type_idx'), models.Index(fields=['identity_type', 'identifier'], name='identity_type_id_idx'), models.Index(fields=['provider', 'provider_user_id'], name='identity_provider_idx')],
                'unique_together': {('identity_type', 'identifier')},
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', '-update_time'], name='tag_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tag_user_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='bbtalk',
            index=models.Index(fields=['user', '-update_time'], name='bbtalk_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bbtalk',
            index=models.Index(fields=['user', '-create_time'], name='bbtalk_user_create_idx'),
        ),
    ]
