# Generated by Django 6.0 on 2026-01-14 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbtalk',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_id',
            field=models.BigIntegerField(db_index=True, verbose_name='用户ID'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='显示名称')),
                ('avatar', models.URLField(blank=True, verbose_name='头像')),
                ('authelia_user_id', models.CharField(blank=True, db_index=True, help_text='来自 Authelia 认证服务的用户唯一标识', max_length=255, null=True, unique=True, verbose_name='Authelia用户ID')),
                ('groups', models.JSONField(blank=True, default=list, verbose_name='用户组')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['authelia_user_id'], name='user_authelia_idx'), models.Index(fields=['username'], name='user_username_idx')],
            },
        ),
    ]
