# Generated by Django 6.0 on 2026-02-10 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='storage_config_id',
            field=models.CharField(blank=True, db_index=True, help_text='S3存储配置的唯一标识，为空表示使用本地存储或系统默认配置', max_length=100, null=True, verbose_name='存储配置ID'),
        ),
        migrations.CreateModel(
            name='UserStorageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_type', models.CharField(choices=[('local', '本地存储'), ('s3', 'S3 兼容存储')], default='local', max_length=16, verbose_name='存储类型')),
                ('s3_access_key_id', models.CharField(blank=True, max_length=255, verbose_name='Access Key ID')),
                ('s3_secret_access_key', models.CharField(blank=True, help_text='密钥将加密存储', max_length=255, verbose_name='Secret Access Key')),
                ('s3_bucket_name', models.CharField(blank=True, max_length=255, verbose_name='存储桶名称')),
                ('s3_region_name', models.CharField(blank=True, default='us-east-1', max_length=64, verbose_name='区域')),
                ('s3_endpoint_url', models.URLField(blank=True, help_text='用于 MinIO、阿里云 OSS 等 S3 兼容服务', max_length=500, verbose_name='端点 URL')),
                ('s3_custom_domain', models.CharField(blank=True, help_text='用于 CDN 或自定义域名访问', max_length=255, verbose_name='自定义域名')),
                ('is_active', models.BooleanField(default=False, help_text='是否启用自定义存储', verbose_name='启用')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户存储设置',
                'verbose_name_plural': '用户存储设置',
                'db_table': 'cb_user_storage_settings',
            },
        ),
    ]
