# Generated by Django 5.2.7 on 2025-11-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbtalk',
            name='update_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
    ]
