# Generated by Django 5.2.7 on 2025-11-13 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0002_alter_bbtalk_update_time'),
        ('media', '0002_alter_media_update_time'),
        ('tags', '0005_tag_tag_user_deleted_time_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bbtalk',
            index=models.Index(fields=['user', 'is_deleted', '-update_time'], name='bbtalk_user_deleted_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bbtalk',
            index=models.Index(fields=['user', 'is_deleted', '-create_time'], name='bbtalk_user_deleted_create_idx'),
        ),
    ]
