# Generated by Django 6.0 on 2026-02-10 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0002_attachment_storage_config_id_userstoragesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstoragesettings',
            name='name',
            field=models.CharField(default='默认配置', help_text='例如：阿里云OSS、MinIO测试、AWS S3', max_length=100, verbose_name='配置名称'),
        ),
        migrations.AlterField(
            model_name='userstoragesettings',
            name='storage_type',
            field=models.CharField(choices=[('local', '本地存储'), ('s3', 'S3 兼容存储')], default='s3', max_length=16, verbose_name='存储类型'),
        ),
        migrations.AlterField(
            model_name='userstoragesettings',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userstoragesettings',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='userstoragesettings',
            index=models.Index(fields=['user', 'is_active'], name='storage_user_active_idx'),
        ),
    ]
