# Generated by Django 6.0 on 2026-01-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0002_alter_bbtalk_user_id_alter_tag_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbtalk',
            name='tags',
            field=models.ManyToManyField(db_constraint=False, db_table='cb_bbtalk_tags_relations', related_name='bbtalks', to='bbtalk.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='bbtalk',
            name='user_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bbtalk.user', verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user_id',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='bbtalk.user', verbose_name='用户ID'),
        ),
        migrations.AlterModelTable(
            name='bbtalk',
            table='cb_user_bbtalks',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='cb_user_tags',
        ),
        migrations.AlterModelTable(
            name='user',
            table='cb_users',
        ),
    ]
