# Generated by Django 6.0 on 2026-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0003_userstoragesettings_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbtalk',
            options={'ordering': ['-is_pinned', '-update_time'], 'verbose_name': '碎碎念', 'verbose_name_plural': '碎碎念'},
        ),
        migrations.AddField(
            model_name='bbtalk',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否置顶'),
        ),
    ]
