# Generated by Django 6.0 on 2026-04-20 02:56

import bbtalk.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0004_add_is_pinned_to_bbtalk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=bbtalk.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('bbtalk', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bbtalk.bbtalk', verbose_name='碎碎念')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'cb_comments',
                'ordering': ['create_time'],
                'indexes': [models.Index(fields=['bbtalk', 'create_time'], name='comment_bbtalk_time_idx'), models.Index(fields=['user', '-create_time'], name='comment_user_time_idx')],
            },
        ),
    ]
