# Generated by Django 6.0 on 2026-09-07 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbtalk.bbtalk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_submission_receipts',
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='submission_user_key_unique')],
            },
        ),
    ]
