# Generated by Django 6.0 on 2026-09-18 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0006_submission_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopAuthorization',
            fields=[
                ('code_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('challenge', models.CharField(max_length=43)),
                ('redirect_uri', models.CharField(max_length=200)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_desktop_authorizations',
            },
        ),
    ]
