# Generated by Django 6.0 on 2026-09-20 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbtalk', '0008_attachment_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credential_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('credential_version', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cb_password_recovery',
            },
        ),
    ]
