import { act, cleanup, renderHook } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { usePrivacyMode } from '../src/hooks/usePrivacyMode'
beforeEach(() => { vi.useFakeTimers(); localStorage.clear() })
afterEach(() => { cleanup(); vi.clearAllTimers(); vi.useRealTimers(); vi.restoreAllMocks() })
it('restores a saved lock synchronously and never unlocks on ordinary activity', () => {
  localStorage.setItem('bbtalk_privacy_mode', 'true')
  const { result } = renderHook(() => usePrivacyMode({ timeout: 2000 }))
  expect(result.current.isPrivacyMode).toBe(true)
  act(() => { window.dispatchEvent(new Event('click')); vi.advanceTimersByTime(3000) })
  expect(result.current.isPrivacyMode).toBe(true)
})
it('locks at timeout and hides the countdown after locking', () => {
  const { result } = renderHook(() => usePrivacyMode({ timeout: 3000, trackCountdown: true }))
  expect(result.current.remainingSeconds).toBe(3)
  act(() => vi.advanceTimersByTime(1000))
  expect(result.current.remainingSeconds).toBe(2)
  act(() => vi.advanceTimersByTime(2000))
  expect(result.current.isPrivacyMode).toBe(true)
  expect(result.current.remainingSeconds).toBeNull()
  expect(localStorage.getItem('bbtalk_privacy_mode')).toBe('true')
})
it.each(['mousedown', 'keydown', 'scroll', 'touchstart', 'click'])('extends the inactivity timeout on %s', event => {
  const { result } = renderHook(() => usePrivacyMode({ timeout: 3000 }))
  act(() => vi.advanceTimersByTime(2000))
  act(() => window.dispatchEvent(new Event(event)))
  act(() => vi.advanceTimersByTime(2000))
  expect(result.current.isPrivacyMode).toBe(false)
  act(() => vi.advanceTimersByTime(1000))
  expect(result.current.isPrivacyMode).toBe(true)
})
it('clears the saved lock on explicit unlock and starts a new countdown', () => {
  localStorage.setItem('bbtalk_privacy_mode', 'true')
  localStorage.setItem('bbtalk_privacy_timestamp', '1')
  const { result } = renderHook(() => usePrivacyMode({ timeout: 2000 }))
  act(() => result.current.deactivatePrivacy())
  expect(localStorage.getItem('bbtalk_privacy_mode')).toBeNull()
  expect(localStorage.getItem('bbtalk_privacy_timestamp')).toBeNull()
  act(() => vi.advanceTimersByTime(1999))
  expect(result.current.isPrivacyMode).toBe(false)
  act(() => vi.advanceTimersByTime(1))
  expect(result.current.isPrivacyMode).toBe(true)
})
it('reschedules when the timeout setting changes', () => {
  const { result, rerender } = renderHook(timeout => usePrivacyMode({ timeout }), { initialProps: 5000 })
  act(() => vi.advanceTimersByTime(1000)); rerender(2000)
  act(() => vi.advanceTimersByTime(2000))
  expect(result.current.isPrivacyMode).toBe(true)
})
it('does not restore or create a lock when privacy is disabled', () => {
  localStorage.setItem('bbtalk_privacy_mode', 'true')
  const { result } = renderHook(() => usePrivacyMode({ enabled: false, timeout: 1000 }))
  act(() => vi.advanceTimersByTime(3000))
  expect(result.current.isPrivacyMode).toBe(false)
  expect(result.current.remainingSeconds).toBeNull()
})
it('keeps non-persistent locks out of browser storage', () => {
  const { result } = renderHook(() => usePrivacyMode({ persistOnRefresh: false }))
  act(() => result.current.activatePrivacy())
  expect(result.current.isPrivacyMode).toBe(true)
  expect(localStorage.getItem('bbtalk_privacy_mode')).toBeNull()
  act(() => result.current.resetTimer())
  expect(result.current.isPrivacyMode).toBe(false)
})
it('removes activity listeners and timers on unmount', () => {
  const remove = vi.spyOn(window, 'removeEventListener')
  const { unmount } = renderHook(() => usePrivacyMode({ trackCountdown: true }))
  unmount()
  for (const event of ['mousedown', 'keydown', 'scroll', 'touchstart', 'click']) expect(remove).toHaveBeenCalledWith(event, expect.any(Function))
  expect(vi.getTimerCount()).toBe(0)
})
