import { test, expect, type Page } from '@playwright/test'

async function login(page: Page) {
  const username = `draft_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`
  const password = 'draft-e2e-2026'
  expect((await page.request.post('/api/v1/bbtalk/auth/register/', { data: { username, password } })).status()).toBe(201)
  await page.goto('/login')
  await page.getByPlaceholder('请输入用户名').fill(username)
  await page.getByPlaceholder('请输入密码').fill(password)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page.getByLabel('记录内容')).toBeEnabled()
}

test('restores full draft and pending file bytes, then clears after successful publish', async ({ page }, info) => {
  await login(page)
  await page.getByLabel('记录内容').fill('#草稿标签 刷新仍在的内容')
  await page.getByTitle('仅自己可见', { exact: true }).click()
  await page.route('**/api/v1/attachments/files/', route => route.abort('internetdisconnected'))
  await page.getByLabel('上传附件', { exact: true }).setInputFiles({ name: 'draft.txt', mimeType: 'text/plain', buffer: Buffer.from('persistent file bytes') })
  await expect(page.getByText('网络连接失败，请检查网络后重试')).toBeVisible()
  await expect(page.getByRole('status')).toContainText('草稿已保存')
  await page.reload()
  await expect(page.getByLabel('记录内容')).toHaveValue('#草稿标签 刷新仍在的内容')
  await expect(page.getByTitle('公开可见', { exact: true })).toBeVisible()
  await expect(page.getByText('未完成上传，请重试')).toBeVisible()
  await page.screenshot({ path: info.outputPath('restored-draft.png'), fullPage: true })
  await page.unroute('**/api/v1/attachments/files/')
  const uploaded = page.waitForResponse(response => response.request().method() === 'POST' && response.url().includes('/attachments/files/'))
  await page.getByRole('button', { name: '重试上传' }).click()
  const attachment = await (await uploaded).json()
  expect(await (await page.request.get(attachment.preview_url || attachment.url || attachment.file)).text()).toBe('persistent file bytes')
  await expect(page.getByRole('button', { name: '移除附件 draft.txt' })).toBeVisible()
  await expect(page.getByRole('status')).toContainText('草稿已保存')
  await page.reload()
  await expect(page.getByRole('button', { name: '移除附件 draft.txt' })).toBeVisible()
  await page.route('**/api/v1/bbtalk/', route => route.request().method() === 'POST' ? route.abort('internetdisconnected') : route.continue())
  await page.getByRole('button', { name: '发布', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('发布失败')
  await page.reload()
  await expect(page.getByLabel('记录内容')).toHaveValue('#草稿标签 刷新仍在的内容')
  await page.unroute('**/api/v1/bbtalk/')
  await page.getByRole('button', { name: '发布', exact: true }).click()
  await expect(page.getByLabel('记录内容')).toHaveValue('')
  await page.reload()
  await expect(page.getByLabel('记录内容')).toHaveValue('')
  await expect(page.locator('.bbtalk-item').first()).toContainText('刷新仍在的内容')
  await expect(page.locator('.bbtalk-item').first()).toContainText('草稿标签')
})

test('explicit clear survives refresh and stale tabs cannot resurrect deleted draft', async ({ page, context }) => {
  await login(page)
  await page.getByLabel('记录内容').fill('待清除内容')
  await expect(page.getByRole('status')).toContainText('草稿已保存')
  const other = await context.newPage()
  await other.goto('/')
  await expect(other.getByLabel('记录内容')).toHaveValue('待清除内容')
  await page.getByRole('button', { name: '清除草稿', exact: true }).click()
  await page.getByRole('button', { name: '确认清除', exact: true }).click()
  await expect(page.getByLabel('记录内容')).toHaveValue('')
  await other.getByLabel('记录内容').fill('旧标签页修改')
  await expect(other.getByRole('alert')).toContainText('另一标签页')
  await expect(other.getByLabel('记录内容')).toHaveValue('旧标签页修改')
  await page.reload()
  await expect(page.getByLabel('记录内容')).toHaveValue('')
})

test('storage rejection preserves input with visible failure', async ({ page }) => {
  await login(page)
  await page.evaluate(() => { IDBObjectStore.prototype.put = function () { throw new DOMException('浏览器存储空间不足', 'QuotaExceededError') } })
  await page.getByLabel('记录内容').fill('存储失败仍保留')
  await expect(page.getByRole('alert')).toContainText('存储空间不足')
  await expect(page.getByLabel('记录内容')).toHaveValue('存储失败仍保留')
})

test('navigation restores separate new and edit drafts', async ({ page }) => {
  await login(page)
  for (const content of ['记录甲', '记录乙']) {
    await page.getByLabel('记录内容').fill(content)
    await page.getByRole('button', { name: '发布', exact: true }).click()
    await expect(page.getByLabel('记录内容')).toHaveValue('')
  }
  const recordId = await page.locator('.bbtalk-item').filter({ hasText: '记录甲' }).getAttribute('data-record-id')
  const card = page.locator(`[data-record-id="${recordId}"]`)
  await page.getByLabel('记录内容').fill('独立新建草稿')
  await card.getByTitle('更多', { exact: true }).click()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await card.getByLabel('记录内容').fill('记录甲未提交修改')
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await expect(page).toHaveURL(/\/settings$/)
  await expect(page.getByRole('heading', { name: '设置', exact: true })).toBeVisible()
  await page.goBack()
  await expect(page).toHaveURL(/\/$/)
  await expect(card.getByTitle('更多', { exact: true })).toBeVisible()
  await expect(page.getByLabel('记录内容').first()).toHaveValue('独立新建草稿')
  const second = page.locator('.bbtalk-item').first()
  await second.getByTitle('更多', { exact: true }).click()
  await second.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(second.getByLabel('记录内容')).toHaveValue('记录乙')
  await second.getByRole('button', { name: '取消', exact: true }).click()
  await card.getByTitle('更多', { exact: true }).click()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(card.getByLabel('记录内容')).toHaveValue('记录甲未提交修改')
  await card.getByRole('button', { name: '保存', exact: true }).click()
  await expect(card.getByLabel('记录内容')).toHaveCount(0)
  await page.reload()
  await expect(page.getByLabel('记录内容')).toHaveValue('独立新建草稿')
  await card.getByTitle('更多', { exact: true }).click()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(card.getByLabel('记录内容')).toHaveValue('记录甲未提交修改')
  await expect(card.getByRole('status')).toContainText('输入后自动保存')
})

test('accounts keep separate drafts in the same browser', async ({ page }) => {
  await login(page)
  await page.getByLabel('记录内容').fill('账号甲私有草稿')
  await expect(page.getByRole('status')).toContainText('草稿已保存')
  const accountA = await page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([key]) => key.startsWith('bbtalk_'))))
  await page.evaluate(() => { for (const key of ['bbtalk_access_token', 'bbtalk_refresh_token', 'bbtalk_user_info']) localStorage.removeItem(key) })
  await login(page)
  await expect(page.getByLabel('记录内容')).toHaveValue('')
  await page.getByLabel('记录内容').fill('账号乙私有草稿')
  await expect(page.getByRole('status')).toContainText('草稿已保存')
  await page.evaluate(values => { Object.entries(values).forEach(([key, value]) => localStorage.setItem(key, value)) }, accountA)
  await page.reload()
  await expect(page.getByLabel('记录内容')).toHaveValue('账号甲私有草稿')
})

test('publishing a new draft while editing creates a record and keeps the edit draft', async ({ page }) => {
  await login(page)
  await page.getByLabel('记录内容').fill('原始记录')
  await page.getByRole('button', { name: '发布', exact: true }).click()
  await expect(page.getByLabel('记录内容')).toHaveValue('')
  const original = page.locator('.bbtalk-item').first()
  await original.getByTitle('更多', { exact: true }).click()
  await original.getByRole('button', { name: '编辑', exact: true }).click()
  await original.getByLabel('记录内容').fill('尚未保存的编辑')
  await page.getByLabel('记录内容').first().fill('独立发布的新记录')
  await page.getByRole('button', { name: '发布', exact: true }).click()
  await expect(page.locator('.bbtalk-item')).toHaveCount(2)
  await expect(page.locator('.bbtalk-item').nth(1).getByLabel('记录内容')).toHaveValue('尚未保存的编辑')
  await page.reload()
  await expect(page.locator('.bbtalk-item').nth(1)).toContainText('原始记录')
  await expect(page.locator('.bbtalk-item').first()).toContainText('独立发布的新记录')
})

test('restored edit warns when the server record changed', async ({ page }) => {
  await login(page)
  await page.getByLabel('记录内容').fill('原始版本')
  await page.getByRole('button', { name: '发布', exact: true }).click()
  await expect(page.getByLabel('记录内容')).toHaveValue('')
  const card = page.locator('.bbtalk-item').first()
  const id = await card.getAttribute('data-record-id')
  await card.getByTitle('更多', { exact: true }).click()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await card.getByLabel('记录内容').fill('未提交的旧版本草稿')
  await expect(card.getByRole('status')).toContainText('草稿已保存')
  await card.getByRole('button', { name: '取消', exact: true }).click()
  const token = await page.evaluate(() => localStorage.getItem('bbtalk_access_token'))
  expect((await page.request.patch(`/api/v1/bbtalk/${id}/`, { headers: { Authorization: `Bearer ${token}` }, data: { content: '另一客户端更新' } })).ok()).toBe(true)
  await page.reload()
  await expect(card).toContainText('另一客户端更新')
  await card.getByTitle('更多', { exact: true }).click()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(card.getByLabel('记录内容')).toHaveValue('未提交的旧版本草稿')
  await expect(card.getByRole('alert')).toContainText('原记录已有更新')
  await card.getByLabel('记录内容').fill('继续修改旧草稿')
  await expect(card.getByRole('status')).toContainText('草稿已保存')
  await page.reload()
  await card.getByTitle('更多', { exact: true }).click()
  await card.getByRole('button', { name: '编辑', exact: true }).click()
  await expect(card.getByLabel('记录内容')).toHaveValue('继续修改旧草稿')
  await expect(card.getByRole('alert')).toContainText('原记录已有更新')
})
