import { test, expect } from '@playwright/test'

test('comment feedback retains input and supports cancel, keyboard confirmation and retry', async ({ page }, info) => {
  const username = `feedback_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`
  const password = 'feedback-2026'
  expect((await page.request.post('/api/v1/bbtalk/auth/register/', { data: { username, password } })).status()).toBe(201)
  await page.goto('/login')
  await page.getByPlaceholder('请输入用户名').fill(username)
  await page.getByPlaceholder('请输入密码').fill(password)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.getByLabel('记录内容').fill('评论反馈测试记录')
  await page.getByRole('button', { name: '发布', exact: true }).click()
  const card = page.locator('.bbtalk-item').first()
  await card.getByTitle('评论', { exact: true }).click()
  await card.getByLabel('评论内容').fill('原始评论')
  await page.route('**/comments/', route => route.request().method() === 'POST' ? route.abort() : route.continue())
  await card.getByRole('button', { name: '发送', exact: true }).click()
  await expect(card.getByRole('alert')).toContainText('发送失败')
  await expect(card.getByLabel('评论内容')).toHaveValue('原始评论')
  await card.getByLabel('评论内容').fill('后来修改的输入')
  await page.unroute('**/comments/')
  await card.getByRole('button', { name: '重试操作' }).click()
  await expect(card.getByRole('button', { name: '删除评论：原始评论', exact: true })).toBeVisible()
  await expect(card.getByLabel('评论内容')).toHaveValue('后来修改的输入')
  const remove = card.getByRole('button', { name: '删除评论：原始评论', exact: true })
  await remove.click()
  await page.getByRole('dialog', { name: '删除评论' }).getByRole('button', { name: '取消', exact: true }).click()
  await expect(remove).toBeVisible()
  await remove.click()
  await page.route('**/comments/*/', route => route.request().method() === 'DELETE' ? route.abort() : route.continue())
  const dialog = page.getByRole('dialog', { name: '删除评论' })
  await dialog.getByRole('button', { name: '确认删除', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(dialog.getByRole('alert')).toBeVisible()
  await expect(dialog).toContainText('原始评论')
  await page.screenshot({ path: info.outputPath('comment-delete-retry.png'), fullPage: true })
  await page.unroute('**/comments/*/')
  await dialog.getByRole('button', { name: '重试操作', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(remove).not.toBeVisible()
  await expect(card.getByLabel('评论内容')).toHaveValue('后来修改的输入')
})
