# Generated by Django 5.2.7 on 2025-10-21 07:20

import common.models
import django.db.models.deletion
import django.utils.timezone
import media.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('uid', models.CharField(default=common.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('file', media.models.MediaFileFiled(upload_to=media.models.media_upload_to, verbose_name='文件')),
                ('engine', models.IntegerField(choices=[(1, '七牛云'), (2, '本地')], default=1, verbose_name='存储引擎')),
                ('media_type', models.CharField(choices=[('auto', '自动检测'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('attachment', '附件')], default='auto', max_length=20, verbose_name='媒体类型')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='文件描述')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '媒体文件',
                'verbose_name_plural': '媒体文件',
                'db_table': 'user_media',
                'ordering': ['-create_time'],
            },
        ),
    ]
